<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_lenght" value="0.07" />
    <xacro:property name="base_lenght" value="0.7" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.25" />
    <xacro:property name="base_xyz" value="0 0 ${base_height / 2}" />
    <xacro:property name="wheel_rpy" value="${pi / 2.0} 0 0" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="15.0" l="${2*base_lenght}" w="${2*base_width}" h="${2*base_height}" xyz="${base_xyz}" rpy="0 0 0" />
    </link>

    <joint name="footprint_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <xacro:macro name="create_wheel_link" params="prefix">

    <link name="${prefix}_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_lenght}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${wheel_rpy}" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_lenght}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${wheel_rpy}" />
        </collision>
        <xacro:wheel_inertia mass="3.0" l="${2*wheel_lenght}" r="${2*wheel_radius}" xyz="0 0 0" rpy="${wheel_rpy}" />
    </link>

    </xacro:macro> 

    <xacro:create_wheel_link prefix="rear_left" />

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <origin xyz="${-base_lenght / 3.5} ${base_width / 2 + (wheel_lenght / 2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit velocity="100.0" effort="100.0" />
        <!-- <dynamics damping="10.0" friction="10.0" /> that's actually a lot prettyh sure -->
    </joint>

    <xacro:create_wheel_link prefix="rear_right" />

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <origin xyz="${-base_lenght / 3.5} ${-(base_width / 2 + (wheel_lenght / 2))} 0" rpy="0 0 0" />
         <axis xyz="0 1 0" />
    </joint>

    <xacro:create_wheel_link prefix="front_left" />

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_lenght / 3.5} ${base_width / 2 + (wheel_lenght / 2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <xacro:create_wheel_link prefix="front_right" />

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_lenght / 3.5} ${-(base_width / 2 + (wheel_lenght / 2))} 0" rpy="0 0 0" />
         <axis xyz="0 1 0" />
    </joint>

    <!-- <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:caster_wheel_inertia mass="1.5" r="${2*wheel_radius / 2}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_lenght / 4} 0 ${-wheel_radius / 2}" rpy="0 0 0" />
    </joint> -->

</robot>
