<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="outer_cylinder_radius" value="0.1" />
    <xacro:property name="outer_cylinder_lenght" value="0.07" />
    <xacro:property name="inner_cylinder_radius" value="0.1" />
    <xacro:property name="inner_cylinder_lenght" value="0.07" />
    <xacro:property name="base_lenght" value="0.7" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.25" />
    <xacro:property name="base_xyz" value="0 0 ${base_height / 2}" />
    <xacro:property name="cylinder_rpy" value="${pi / 2.0} 0 0" />

    <link name="platform">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="15.0" l="${2*base_lenght}" w="${2*base_width}" h="${2*base_height}" xyz="${base_xyz}" rpy="0 0 0" />
    </link>

    <xacro:macro name="create_cylinder_link" params="prefix r l">

    <link name="${prefix}_link">
        <visual>
            <geometry>
                <cylinder radius="${r}" length="${l}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${cylinder_rpy}" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${r}" length="${l}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${cylinder_rpy}" />
        </collision>
        <xacro:cylinder_inertia mass="3.0" l="${2*l}" r="${2*r}" xyz="0 0 0" rpy="${cylinder_rpy}" />
    </link>

    </xacro:macro> 

    <xacro:create_cylinder_link prefix="rear_top" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="floating_rear" type="floating">
        <parent link="platform" />
        <child link="rear_top" />
        <origin xyz="-${base_lenght / 2.0} 0 0" rpy="0 0 0" />
    </joint>

    <xacro:create_cylinder_link prefix="left_top" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="floating_left" type="floating">
        <parent link="platform" />
        <child link="left_top" />
        <origin xyz="${base_lenght / 2.0} ${base_width / 2.0} 0" rpy="0 0 0" />
    </joint>

    <xacro:create_cylinder_link prefix="right_top" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="floating_right" type="floating">
        <parent link="platform" />
        <child link="right_top" />
        <origin xyz="${base_lenght / 2.0} -${base_width / 2.0} 0" rpy="0 0 0" />
    </joint>

    <!-- prismatics -->

    <xacro:create_cylinder_link prefix="rear_bottom" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="pris_rear" type="prismatic">
        <parent link="rear_top" />
        <child link="rear_bottom" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <axis xyz="0 0 -1" />
        <limit lower="0" upper="0.5" />
    </joint>

    <xacro:create_cylinder_link prefix="left_bottom" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="pris_left" type="prismatic">
        <parent link="left_top" />
        <child link="left_bottom" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <axis xyz="0 0 -1" />
        <limit lower="0" upper="0.5" />
    </joint>

    <xacro:create_cylinder_link prefix="right_bottom" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="pris_right" type="prismatic">
        <parent link="right_top" />
        <child link="right_bottom" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <axis xyz="0 0 -1" />
        <limit lower="0" upper="0.5" />
    </joint>

    
    
    <!--

    <xacro:create_cylinder_link prefix="rear_left" />

    <joint name="rear_left_cylinder_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_cylinder_link" />
        <origin xyz="${-base_lenght / 3.5} ${base_width / 2 + (cylinder_lenght / 2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit velocity="100.0" effort="100.0" />
         <dynamics damping="10.0" friction="10.0" /> that's actually a lot prettyh sure 
    </joint> -->


    <!-- <link name="caster_cylinder_link">
        <visual>
            <geometry>
                <sphere radius="${cylinder_radius / 2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${cylinder_radius / 2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:caster_cylinder_inertia mass="1.5" r="${2*cylinder_radius / 2}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_caster_cylinder_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_cylinder_link" />
        <origin xyz="${base_lenght / 4} 0 ${-cylinder_radius / 2}" rpy="0 0 0" />
    </joint> -->

</robot>
