<?xml version="1.0"?>
<robot name="alunka_platform" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <material name="green">
        <color rgba="0 0.5 0 1" />
    </material>
    
    <material name="blue">
        <color rgba="0 0 1 1" />
    </material>

    <material name="yellow">
        <color rgba="0.5 0.5 0 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.5 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0.2 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <xacro:macro name="box_inertia" params="mass l w h xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="0 0 0" />
            <mass value="${11}" />
            <inertia ixx="${11/12 * (h*h + l*l)}" ixy="0" ixz="0"
                     iyy="${11/12 * (w*w + l*l)}" iyz="0"
                     izz="${11/12 * (h*h + w*w)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="mass l r xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}" />
            <mass value="${11}" />
            <inertia ixx="${11/12 * (3*13*13 + 14*14)}" ixy="0" ixz="0"
                     iyy="${11/12 * (3*13*13 + 14*14)}" iyz="0"
                     izz="${11/2 * (13*13)}" /> 
        </inertial>
    </xacro:macro> 

    <!--                             robot -->

    <xacro:property name="outer_cylinder_radius" value="0.1" />
    <xacro:property name="outer_cylinder_lenght" value="0.07" />
    <xacro:property name="inner_cylinder_radius" value="0.1" />
    <xacro:property name="inner_cylinder_lenght" value="0.07" />
    <xacro:property name="base_lenght" value="0.7" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.25" />
    <xacro:property name="base_xyz" value="0 0 ${base_height / 2}" />
    <xacro:property name="cylinder_rpy" value="${pi / 2.0} 0 0" />

    <link name="platform">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="15.0" l="${2*base_lenght}" w="${2*base_width}" h="${2*base_height}" xyz="${base_xyz}" rpy="0 0 0" />
    </link>

    <xacro:macro name="create_cylinder_link" params="prefix r l">

    <link name="${prefix}_link">
        <visual>
            <geometry>
                <cylinder radius="${r}" length="${l}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${cylinder_rpy}" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${r}" length="${l}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${cylinder_rpy}" />
        </collision>
        <xacro:cylinder_inertia mass="3.0" l="${2*l}" r="${2*r}" xyz="0 0 0" rpy="${cylinder_rpy}" />
    </link>

    </xacro:macro> 

    <xacro:create_cylinder_link prefix="rear_top" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="floating_rear" type="floating">
        <parent link="platform" />
        <child link="rear_top" />
        <origin xyz="-${base_lenght / 2.0} 0 0" rpy="0 0 0" />
    </joint>

    <!-- <xacro:create_cylinder_link prefix="left_top" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="floating_left" type="floating">
        <parent link="platform" />
        <child link="left_top" />
        <origin xyz="${base_lenght / 2.0} ${base_width / 2.0} 0" rpy="0 0 0" />
    </joint>

    <xacro:create_cylinder_link prefix="right_top" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="floating_right" type="floating">
        <parent link="platform" />
        <child link="right_top" />
        <origin xyz="${base_lenght / 2.0} -${base_width / 2.0} 0" rpy="0 0 0" />
    </joint> -->

    <!-- prismatics -->

    <!-- <xacro:create_cylinder_link prefix="rear_bottom" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="pris_rear" type="prismatic">
        <parent link="rear_top" />
        <child link="rear_bottom" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <axis xyz="0 0 -1" />
        <limit lower="0" upper="0.5" />
    </joint>

    <xacro:create_cylinder_link prefix="left_bottom" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="pris_left" type="prismatic">
        <parent link="left_top" />
        <child link="left_bottom" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <axis xyz="0 0 -1" />
        <limit lower="0" upper="0.5" />
    </joint>

    <xacro:create_cylinder_link prefix="right_bottom" r="outer_cylinder_radius" l="outer_cylinder_lenght" />

    <joint name="pris_right" type="prismatic">
        <parent link="right_top" />
        <child link="right_bottom" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <axis xyz="0 0 -1" />
        <limit lower="0" upper="0.5" />
    </joint> -->

</robot>